import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <a href="https://shib.idm.umd.edu/shibboleth-idp/profile/cas/login?service=http%3A%2F%2F127.0.0.1%3A3000%2Fsecure">Login with UMD CAS </a>
      </main>

    </div>
  )
}
